# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190516_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='products.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
