# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190516_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(related_name='posts', to='products.Product'),
        ),
    ]
